# Configuration for Heads v1.1.1 by Gaming12846 <https://www.spigotmc.org/resources/81202/> <https://github.com/Gaming12846/Heads> <https://discord.com/invite/XvK2UMfGEJ>
CheckForUpdates: true

Features:
  HeadRecipeSwitch: true
  
Messages:
  NoPermission: 'You have no permission to do that'
  NoConsole: 'The console cannot use this command'
  UsageGetHead: 'Please use </gethead player>'
  GotOwnHead: 'You got your own head'
  GotPlayerHead: 'You got the head from [Player]'