message:
  nopermission: 'You have no permission to do that'
  noconsole: 'The console cannot use this command'
  usagegethead: 'Please use </gethead Player>'
  getownhead: 'You got your own head'
  getplayerhead: 'You got the head from [Player]'