name: Heads
main: com.github.gaming12846.heads.Heads
version: 1.1.1
description: A simple plugin to get heads from players and things in Minecraft
website: https://www.spigotmc.org/resources/81202/ https://github.com/Gaming12846/Heads https://discord.com/invite/XvK2UMfGEJ
author: Gaming12846
api-version: 1.17


commands:
  gethead:
    description: Gives you your head or another player's head
    usage: Simply type </gethead> or </gethead player>
    aliases: [gh]