name: Heads
version: 1.1
description: A simple plugin to get heads from players and things in Minecraft
author: Gaming12846

main: de.gaming12846.heads.main.Main
api-version: 1.13

commands:
     gethead:
          description: Gives you your own head or that of a player
          aliases: [getheads, gh]
          usage: Simply type </gethead Player>
